### ISSUE TITLE
Get dataset for reproduction

### ISSUE THREAD

**Issue by madmoiselleve** [socialcomplab/recsys21-relistening-actr#1]
Hi ! Thanks for making it available ! 
Is it possible to get the file "input/listening_events_2019.tsv.bz2" that you are using for some notebooks ? I couldn't retrieve it from  http://www.cp.jku.at/datasets/LFM-1b/ .
Many thanks !

**Comment by Iseratho** [comment]
Hi, thanks for your interest in our research.
We use the LFM-2b dataset, which can be retrieved from http://www.cp.jku.at/datasets/LFM-2b/ .
The file is just a subset of listening events from 2019 (i.e., can be created by filtering the full dataset).
Best regards.

**Comment by madmoiselleve** [comment]
Thank you for your answer.
Regards !
